language: node_js
node_js:
  - "node"
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true